/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package btl;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.util.Collections;
import java.util.Comparator;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class QLSVFrame extends javax.swing.JFrame {

    /**
     * Creates new form QLSVFrame
     */
     DefaultTableModel model;
     Data d;
    public QLSVFrame() {
        initComponents();
         model = (DefaultTableModel) jTable1.getModel();
         d = new Data();
        //d.loadData();
         d.loadData();
            for (SinhVien sv : Data.dsSV) {
            Vector vec = new Vector();
            vec.add(sv.getMaSV());
            vec.add(sv.getHoTen());
            vec.add(sv.getDiaChi());
            vec.add(sv.getEmail());
            vec.add(sv.getSoDT());
            vec.add(sv.getDiemTK());
            model.addRow(vec);
        }
        this.setTitle("Chuong trinh quan ly sinh vien");
        this.setLocationRelativeTo(null);
        
    }
    public void SaveData(){
        FileWriter fw = null;
        BufferedWriter bw = null;
        try {
            fw = new FileWriter("src\\data.txt");
            bw = new BufferedWriter(fw);
            String line;
            for (int i = 0; i < Data.dsSV.size(); i++) {
                SinhVien sv = Data.dsSV.get(i);
                line = sv.getMaSV()+","+sv.getHoTen()+","+sv.getDiaChi()+","+sv.getEmail()+","+sv.getSoDT()+","+sv.getDiemTK();
                bw.write(line);
                bw.newLine();
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        } finally{
            try {
                if(bw != null) bw.close();
                if(fw != null) fw.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        } 
    }
    public void showData(){
      
        SinhVien sv = Data.dsSV.get(Data.dsSV.size() - 1);
        model.addRow(new Object[]{sv.getMaSV(),sv.getHoTen(),sv.getDiaChi(),sv.getEmail(),sv.getSoDT(),sv.getDiemTK()});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        msvfoundtxt = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        huybtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        msvtxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        diachitxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        phonetxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        emailtxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        diemtxt = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        addbtn = new javax.swing.JButton();
        suabtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        sorcebtn = new javax.swing.JButton();
        resetbtn = new javax.swing.JButton();
        showbtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setText("Mã Sinh Viên");

        msvfoundtxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        searchbtn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        searchbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive\\Documents\\NetBeansProjects\\DemoHelloWorld\\BTL\\src\\Icon\\Search-icon.png")); // NOI18N
        searchbtn.setText("Tìm kiếm");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        huybtn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        huybtn.setText("Hủy");
        huybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huybtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("DANH SÁCH SINH VIÊN");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ma Sinh Vien", "Ho Ten", "Dia Chi", "Email", "So Dien Thoai", "Diem Tong Ket"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Thông tin sinh viên");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setText("Mã Sinh Viên");

        msvtxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        msvtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                msvtxtFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setText("Họ Tên");

        nametxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        nametxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nametxtFocusLost(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel6.setText("Địa Chỉ");

        diachitxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel7.setText("Số Điện Thoại");

        phonetxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel8.setText("Email");

        emailtxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        emailtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailtxtFocusLost(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel9.setText("Điểm Tổng Kết");

        diemtxt.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        diemtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diemtxtActionPerformed(evt);
            }
        });

        addbtn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        addbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive\\Documents\\NetBeansProjects\\DemoHelloWorld\\BTL\\src\\Icon\\Plus-icon.png")); // NOI18N
        addbtn.setText("Thêm");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        suabtn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        suabtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive\\Documents\\NetBeansProjects\\DemoHelloWorld\\BTL\\src\\Icon\\Refresh-icon.png")); // NOI18N
        suabtn.setText("Sửa");
        suabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suabtnActionPerformed(evt);
            }
        });

        deletebtn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        deletebtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive\\Documents\\NetBeansProjects\\DemoHelloWorld\\BTL\\src\\Icon\\deleteIcon.png")); // NOI18N
        deletebtn.setText("Xóa");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        sorcebtn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        sorcebtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive\\Documents\\NetBeansProjects\\DemoHelloWorld\\BTL\\src\\Icon\\Actions-view-sort-descending-icon.png")); // NOI18N
        sorcebtn.setText("Xắp Xếp Theo Tên");
        sorcebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sorcebtnActionPerformed(evt);
            }
        });

        resetbtn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        resetbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive\\Documents\\NetBeansProjects\\DemoHelloWorld\\BTL\\src\\Icon\\reset.png")); // NOI18N
        resetbtn.setText("Reset");
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });

        showbtn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        showbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\OneDrive\\Documents\\NetBeansProjects\\DemoHelloWorld\\BTL\\src\\Icon\\information-icon.png")); // NOI18N
        showbtn.setText("Hiên thị thông tin");
        showbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showbtnActionPerformed(evt);
            }
        });

        jMenu3.setText("About");

        jMenuItem5.setText("About Me");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("More");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(msvfoundtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(searchbtn)
                                .addGap(53, 53, 53)
                                .addComponent(huybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(389, 389, 389)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(msvtxt)
                                    .addComponent(nametxt)
                                    .addComponent(diachitxt, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                                .addGap(101, 101, 101)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(phonetxt)
                                            .addComponent(emailtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(diemtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(suabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(showbtn)
                .addGap(36, 36, 36)
                .addComponent(sorcebtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(resetbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(huybtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(msvfoundtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(searchbtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(msvtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(phonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(diachitxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(diemtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletebtn)
                    .addComponent(suabtn)
                    .addComponent(addbtn)
                    .addComponent(sorcebtn)
                    .addComponent(resetbtn)
                    .addComponent(showbtn))
                .addGap(76, 76, 76))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diemtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diemtxtActionPerformed
          
            
    }//GEN-LAST:event_diemtxtActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
         boolean check = true;
        SinhVien sv = new SinhVien();
        sv.setMaSV(this.msvtxt.getText());
        sv.setHoTen(this.nametxt.getText());
        sv.setDiaChi(this.diachitxt.getText());
        sv.setEmail(this.emailtxt.getText());
        try {
            sv.setSoDT(Integer.parseInt(this.phonetxt.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Số điện thoại chỉ chứa số và không chứa bất kỳ một ký tự nào khác");
            check = false;
        }
        try {
           Double diem  = Double.parseDouble(this.diemtxt.getText());
           if(diem >= 0 && diem <= 10){
               sv.setDiemTK(diem);
           }else{
               JOptionPane.showMessageDialog(rootPane, "Điểm nằm trong khoảng từ 0 - 10");
               check = false;
           }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Điểm sinh viên phải là số và không được phép chứa các ký tự");
            check = false;
        }
        if(check){
            Data.dsSV.add(sv);
            JOptionPane.showMessageDialog(rootPane, "Thêm sinh viên thành công");
            SaveData();
            showData();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Thêm sinh viên thất bại");
        }
    }//GEN-LAST:event_addbtnActionPerformed

    private void suabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suabtnActionPerformed
        
        int chon = jTable1.getSelectedRow();
        if(Data.dsSV.size() == 0){
            JOptionPane.showMessageDialog(rootPane, "Bạn phải thêm sinh viên vào danh sách trước khi tiến hành cập nhập lại thông tin sinh viên");
        }
        if(chon == -1){
            JOptionPane.showMessageDialog(rootPane, "Bạn phải chọn 1 sinh viên trước");
        }else{
        
        SinhVien sv = new SinhVien();
        sv.setMaSV(this.msvtxt.getText());
        sv.setHoTen(this.nametxt.getText());
        sv.setDiaChi(this.diachitxt.getText());
        sv.setEmail(this.emailtxt.getText());
        sv.setSoDT(Integer.parseInt(this.phonetxt.getText()));
        sv.setDiemTK(Double.parseDouble(this.diemtxt.getText()));
        Data.dsSV.set(chon, sv);
        model.setValueAt(sv.getHoTen(), chon, 1);
        model.setValueAt(sv.getDiaChi(), chon, 2);
        model.setValueAt(sv.getEmail(), chon, 3);
        model.setValueAt(sv.getSoDT(), chon, 4);
        model.setValueAt(sv.getDiemTK(), chon, 5);
        JOptionPane.showMessageDialog(rootPane, "Sửa thành công");
        SaveData();
        }
    }//GEN-LAST:event_suabtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        int chonxoa = jTable1.getSelectedRow();
        
       if(Data.dsSV.size() == 0){
           JOptionPane.showMessageDialog(rootPane, "Dánh sách sinh viên hiện đang không có 1 sinh viên nào cả");
       }
       if(chonxoa == -1){
           JOptionPane.showMessageDialog(rootPane, "Bạn phải chọn 1 sinh viên muốn xóa khỏi danh sách");
       }else{
           int chon = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc muốn xóa sinh viên này ra khỏi danh sách hay không", "", JOptionPane.YES_NO_OPTION);
           if(chon == JOptionPane.YES_OPTION){
            model.removeRow(chonxoa);
            Data.dsSV.remove(chonxoa);
        
             SaveData();
       }
       }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void sorcebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sorcebtnActionPerformed
        Collections.sort(Data.dsSV,  new Comparator<SinhVien>() {
            @Override
            public int compare(SinhVien o1, SinhVien o2) {
                int cmp = o1.getHoTen().compareTo(o2.getHoTen());
                if(cmp >= 0) return 1;
                else
                    return -1;
            }
        });
        model.setRowCount(0);
        for (SinhVien sv : Data.dsSV) {
            model.addRow(new Object[]{sv.getMaSV(),sv.getHoTen(),sv.getDiaChi(),sv.getEmail(),sv.getSoDT(),sv.getDiemTK()});
        }
        SaveData();
    }//GEN-LAST:event_sorcebtnActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
       this.msvtxt.setText("");
       this.nametxt.setText("");
       this.diachitxt.setText("");
       this.emailtxt.setText("");
       this.phonetxt.setText("");
       this.diemtxt.setText("");
      
    }//GEN-LAST:event_resetbtnActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
       String msvfound = this.msvfoundtxt.getText();
       model.setRowCount(0);
       int count = 0;
        for (SinhVien sv : Data.dsSV) {
            if(sv.getMaSV().equals(msvfound)){
                 model.addRow(new Object[]{sv.getMaSV(),sv.getHoTen(),sv.getDiaChi(),sv.getEmail(),sv.getSoDT(),sv.getDiemTK()});
                 count++;
            }
        }
        if(count == 0){
            JOptionPane.showMessageDialog(rootPane, "Sinh viên này không tồn tại trong danh sách");
        }
    }//GEN-LAST:event_searchbtnActionPerformed

    private void huybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huybtnActionPerformed
        model.setRowCount(0);
        for (SinhVien sv : Data.dsSV) {
            model.addRow(new Object[]{sv.getMaSV(),sv.getHoTen(),sv.getDiaChi(),sv.getEmail(),sv.getSoDT(),sv.getDiemTK()});
        }
    }//GEN-LAST:event_huybtnActionPerformed

    private void msvtxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_msvtxtFocusLost
        if(this.msvtxt.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Mã sinh viên không được để trống");
        }
    }//GEN-LAST:event_msvtxtFocusLost

    private void emailtxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailtxtFocusLost
        if(this.emailtxt.getText().indexOf("@") < 0){
            JOptionPane.showMessageDialog(rootPane, "Địa chỉ email cần có đinh dạng abcc@gmail.com");
        }
    }//GEN-LAST:event_emailtxtFocusLost

    private void nametxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nametxtFocusLost
       if(this.nametxt.getText().equals(" ")){
           JOptionPane.showMessageDialog(rootPane, "Sinh viên phải có tên");
       }
    }//GEN-LAST:event_nametxtFocusLost

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       JOptionPane.showMessageDialog(rootPane, "Chương trình quản lý sinh viên phiên bản 1.0");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       int chon1 = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn thoát khói chương trình", "", JOptionPane.YES_NO_OPTION);
       if(chon1 == JOptionPane.YES_OPTION){
           System.exit(0);
       }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void showbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showbtnActionPerformed
       int chose = jTable1.getSelectedRow();
       SinhVien sv = Data.dsSV.get(chose);
       this.msvtxt.setText(sv.getMaSV());
       this.nametxt.setText(sv.getHoTen());
       this.diachitxt.setText((sv.getDiaChi()));
       this.emailtxt.setText(sv.getEmail());
       this.diemtxt.setText(sv.getDiemTK() + "");
       this.phonetxt.setText(sv.getSoDT() + "");
    }//GEN-LAST:event_showbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLSVFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLSVFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLSVFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLSVFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLSVFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton deletebtn;
    private javax.swing.JTextField diachitxt;
    private javax.swing.JTextField diemtxt;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JButton huybtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField msvfoundtxt;
    private javax.swing.JTextField msvtxt;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTextField phonetxt;
    private javax.swing.JButton resetbtn;
    private javax.swing.JButton searchbtn;
    private javax.swing.JButton showbtn;
    private javax.swing.JButton sorcebtn;
    private javax.swing.JButton suabtn;
    // End of variables declaration//GEN-END:variables
}
